kind: pipeline
name: default
type: docker

clone:
  recursive: true

steps:
  - name: build
    image: plugins/hugo
    settings:
      extended: true
      hugo_version: 0.99.0
      url: https://gryffyn.io/

  - name: deploy
    image: drillster/drone-rsync
    settings:
      hosts: [ "gryffyn.io" ]
      user:
        from_secret: ssh_user
      key:
        from_secret: ssh_key
      port:
        from_secret: ssh_port
      source: ./public/
      target: /srv/gryffyn.io/public/
      args: --omit-dir-times
