kind: pipeline
name: default
type: docker

steps:
  - name: build
    image: plugins/hugo
    settings:
      validate: true
      hugo_version: 0.92
      url: https://gryffyn.io

  - name: deploy
    image: appleboy/drone-scp
    settings:
      host: gryffyn.io
      username:
        from_secret: ssh_user
      key:
        from_secret: ssh_key
      passphrase:
        from_secret: ssh_pass
      port:
        from_secret: ssh_port
      command_timeout: 2m
      target: /srv/gryffyn.io/
      source: public/*
