kind: pipeline
name: default
type: docker

steps:
  - name: submodules
    image: alpine/git
    commands:
    - git submodule update --init --recursive

  - name: build
    image: plugins/hugo
    settings:
      validate: true
      extended: true
      hugo_version: 0.92.0
      url: https://gryffyn.io/

  - name: deploy
    image: appleboy/drone-scp
    settings:
      host: gryffyn.io
      username:
        from_secret: ssh_user
      key:
        from_secret: ssh_key
      passphrase:
        from_secret: ssh_pass
      port:
        from_secret: ssh_port
      command_timeout: 2m
      target: /srv/gryffyn.io/public/
      source: public/*
      strip_components: 1
      rm: true
