baseurl: "https://gryffyn.io/"
title: "gryffyn.io"
theme: "hugo-f5-dark"
languageCode: "en-us"
pygmentsUseClasses: true
relativeURLs: true
# enableGitInfo: true
enableRobotsTXT: true
#frontmatter:
#  date:
#    - ":filename"
#    - ":default"
#    - ":fileModTime"
params:
  title: "gryffyn"
  description: "blog posts about tech and queerness"
  titleCutting: true
  goatcounter: true
  gcURL: "https://stat.gryffyn.io/"
  info:
    author: "gryffyn"
    link: "https://github.com/gryffyn"
  sections:
    about: true
    posts: true
  socialLinks:
    - name: git
      url: "https://git.gryffyn.io/gryffyn"
    - name: github
      url: "https://github.com/gryffyn"
    - name: twitter
      url: "https://twitter.com/gryffynmp"
  navlinks:
    - name: about/
      url: about/
    - name: posts/
      url: posts/
    - name: galleries/
      url: galleries/
